version: '3.2'
services:

  ecb:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/diadata/build/Dockerfile-ecb
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_ecb:latest
    networks:
      - redis-network
    logging:
      options:
        max-size: "50m"

  hitbtccollector:
    depends_on: [genericcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericcollector:latest
    command: /bin/collector -exchange=HitBTC -onePairPerSymbol
    networks:
      - kafka-network
      - redis-network
    logging:
      options:
        max-size: "50m"

  gateiocollector:
    depends_on: [genericcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericcollector:latest
    command: /bin/collector -exchange=GateIO
    networks:
      - kafka-network
      - redis-network
    logging:
      options:
        max-size: "50m"

  genericcollector:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/diadata/build/Dockerfile-genericCollector
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericcollector:latest
    restart: "no"
    networks:
      - kafka-network
      - redis-network
    logging:
      options:
        max-size: "50m"


  simexcollector:
    depends_on: [genericcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericcollector:latest
    command: /bin/collector -exchange=Simex
    networks:
      - kafka-network
      - redis-network
    logging:
      options:
        max-size: "50m"

  bittrexcollector:
    depends_on: [genericcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericcollector:latest
    command: /bin/collector -exchange=Bittrex
    networks:
      - kafka-network
      - redis-network
    logging:
      options:
        max-size: "50m"

  lbankcollector:
    depends_on: [genericcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericcollector:latest
    command: /bin/collector -exchange=LBank
    networks:
      - kafka-network
      - redis-network
    logging:
      options:
        max-size: "50m"

  okexcollector:
    depends_on: [genericcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericcollector:latest
    command: /bin/collector -exchange=OKEx -onePairPerSymbol
    networks:
      - kafka-network
      - redis-network
    logging:
      options:
        max-size: "50m"

  huobicollector:
    depends_on: [genericcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericcollector:latest
    command: /bin/collector -exchange=Huobi
    networks:
      - kafka-network
      - redis-network
    logging:
      options:
        max-size: "50m"

  coinbasecollector:
    depends_on: [genericcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericcollector:latest
    command: /bin/collector -exchange=CoinBase
    networks:
      - kafka-network
      - redis-network
    logging:
      options:
        max-size: "50m"

  binancecollector:
    depends_on: [genericcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericcollector:latest
    command: /bin/collector -exchange=Binance
    networks:
      - kafka-network
      - redis-network
    secrets:
      - api_binance
    logging:
      options:
        max-size: "50m"

  bitfinexcollector:
    depends_on: [genericcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericcollector:latest
    command: /bin/collector -exchange=Bitfinex
    networks:
      - kafka-network
      - redis-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_bitfinex

  krakencollector:
    depends_on: [genericcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericcollector:latest
    command: /bin/collector -exchange=Kraken
    networks:
      - kafka-network
      - redis-network
    logging:
      options:
        max-size: "50m"

  zbcollector:
    depends_on: [genericcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericcollector:latest
    command: /bin/collector -exchange=ZB
    networks:
      - kafka-network
      - redis-network
    logging:
      options:
        max-size: "50m"

  quoinecollector:
    depends_on: [genericcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericcollector:latest
    command: /bin/collector -exchange=Quoine
    networks:
      - kafka-network
      - redis-network
    logging:
      options:
        max-size: "50m"

  bitbaycollector:
    depends_on: [genericcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericcollector:latest
    command: /bin/collector -exchange=BitBay
    networks:
      - kafka-network
      - redis-network
    logging:
      options:
        max-size: "50m"

secrets:
  api_binance:
    file: ../secrets/api_binance.json
  api_bitfinex:
    file: ../secrets/api_bitfinex.json
  api_kraken:
    file: ../secrets/api_kraken.json

networks:
  kafka-network:
    external:
        name: kafka_kafka-network
  redis-network:
    external:
        name: redis_redis-network
  influxdb-network:
    external:
        name: influxdb_influxdb-network
