version: '3.2'

services:
  geth:
    image:
      ethereum/client-go:stable
    volumes:
      - /home/srv/geth:/root/.ethereum
    command: --rpcvhosts geth --rpc --rpcaddr "0.0.0.0" --cache 1024 --rpc --syncmode "fast" --ws --ws.addr "0.0.0.0" --ws.origins "*" --ws.port 8546 --http.api admin,db,eth,debug,miner,net,shh,txpool,personal,web3 --txpool.globalqueue 4096
    ports: 
      - mode: host
        target: 8545
        published: 8545
      - mode: host
        target: 8546
        published: 8546
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      restart_policy:
        delay: 2s
        window: 20s

  oracleservice:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/diadata/build/Dockerfile-oracleService
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_oracleservice
    networks:
      - scrapers-network
    command: --deployedContract=0xD47FDf51D61c100C447E2D4747c7126F19fa23Ef
    logging:
      options:
        max-size: "50m"
    secrets:
      - oracle_keys

  oracleservice-bsc-testnet:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/diadata/build/Dockerfile-oracleService
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_oracleservice-bsc-testnet
    networks:
      - scrapers-network
    command: --deployedContract=0xf35bEE4B6727D2D1c9167C5fB4D51855D6bB693c --secretsFile=/run/secrets/oracle_keys_bsc_testnet --blockchainNode="https://data-seed-prebsc-1-s1.binance.org:8545" --sleepSeconds=20 --frequencySeconds=3600
    logging:
      options:
        max-size: "50m"
    secrets:
      - oracle_keys_bsc_testnet

  oracleservice-bsc:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/diadata/build/Dockerfile-oracleService
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_oracleservice-bsc
    networks:
      - scrapers-network
    command: --deployedContract=0xf35bEE4B6727D2D1c9167C5fB4D51855D6bB693c --secretsFile=/run/secrets/oracle_keys_bsc --blockchainNode="https://bsc-dataseed.binance.org/" --sleepSeconds=20 --frequencySeconds=86400
    logging:
      options:
        max-size: "50m"
    secrets:
      - oracle_keys_bsc

  diacoingeckooracleservice:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/diadata/build/Dockerfile-diaCoingeckoOracleService
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_diacoingeckooracleservice
    networks:
      - scrapers-network
    command: --deployedContract=0x07E4120dD7411a49e091a20FA0be33a183C35d60 --numCoins=100
    logging:
      options:
        max-size: "50m"
    secrets:
      - oracle_keys

  diacoinmarketcaporacleservice:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/diadata/build/Dockerfile-diaCoinmarketcapOracleService
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_diacoinmarketcaporacleservice
    networks:
      - scrapers-network
    command: --deployedContract=0x48760771feda4be44a6ed3bff13ecbc445159b1d --numCoins=50
    logging:
      options:
        max-size: "50m"
    secrets:
      - oracle_keys
      - Coinmarketcap-API.key

  diascifioracleservice:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/diadata/build/Dockerfile-diaScifiOracleService
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_diascifioracleservice
    networks:
      - scrapers-network
    command: --deployedContract=0x814712cc9fa606a4b372b87cd27775959e052d9a
    logging:
      options:
        max-size: "50m"
    secrets:
      - oracle_keys

secrets:
  api_diadata:
    file: $GOPATH/src/github.com/diadata-org/diadata/secrets/api_diadata.json
  oracle_keys:
    file: $GOPATH/src/github.com/diadata-org/diadata/secrets/oracle_keys.txt
  oracle_keys_bsc_testnet:
    file: $GOPATH/src/github.com/diadata-org/diadata/secrets/oracle_keys_bsc.txt.testnet
  oracle_keys_bsc:
    file: $GOPATH/src/github.com/diadata-org/diadata/secrets/oracle_keys_bsc.txt
  Coinmarketcap-API.key:
    file: $GOPATH/src/github.com/diadata-org/diadata/secrets/Coinmarketcap-API.key

volumes:
  bitcoin:

networks:
  scrapers-network:
