# docker stack deploy -c docker-compose.yml blockchain-scrapers 
version: '3.2'

services:
  bitcoind:
    image:
      kylemanna/bitcoind
    ports:
      - "8332"
    volumes:
      - type: volume
        source: bitcoin
        target: /bitcoin
        volume:
          nocopy: true
    command: btc_oneshot -prune=550 -rpcallowip=::/0 -disablewallet -rpcpassword=mysecretrpcdiapassword -rpcuser=mysecretrpcdiauser
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network

  btc: 
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/api-golang/blockchain-scrapers/Dockerfile-btc
    image: btc:latest
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"

volumes:
  bitcoin:

networks:
  scrapers-network:

secrets:
  api:
    file: config/secrets/api.json