apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: build-create-deploy
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: build-create-deploy
  resources:
    - name: git-source
      resourceRef:
        name: git-diadata-tekton-ci
  params:
    - name: pathToContext
      value: "/workspace/git-source/"
    - name: pathToYamlFile
      value: "deployments/k8s-yaml/filtersblockservice.yaml"
    - name: "imageUrl"
      value: "us.icr.io/dia-registry/scraper/filtersblockservice"
    - name: "imageTag"
      value: "latest"
    - name: pathToDockerfile
      value: "build/Dockerfile-filtersBlockService"
  serviceAccountName: ibm-cr
